### ISSUE TITLE
Box setup

### ISSUE THREAD

**Issue by viktoria-schwarz** [reservix-ui/marigold#43]
Compare theme-ui, seek-oss Boxes.
Collect ideas what the Box should (not) do

- write test cases for box

**Comment by ti10le** [comment]
https://chakra-ui.com/box

**Comment by ti10le** [comment]
The best abstraction to reuse styling in modern frontend development is a `<Box/>` component. This component encapsulates properties of the design system, such that you can not violate them, and exposes an easy to use API for developers via familiar concepts: `props`. We orient ourselves by the box component from theme-ui. (https://github.com/system-ui/theme-ui/blob/master/packages/components/src/Box.js)
This means not that we copy and paste them. We discuss about all parts of the box. First we collect things the box should (not) do.

What the box should do and should include:
- give a frame for all components
- single source of truth
- enforce the values specified by the design system
- control spacing, size, colors and alignment
- styled component for every box usage (standard: as 'div')
- 3 parts of props
	- base: minimal styles, browser normalization
	- theme: get styles from a defined theme (like rx or adticket theme) via key (styles.button.default or theme.button.primary)
	- css/style props: user can define special css for individual components

What the box shouldn't do:
- not too many restrictions
- not to complicated to understand and to use

**Comment by ti10le** [comment]
Box component test cases:

- render a default box component without any props
	- expected result: rendered component is a html div element
- change box component via 'as' prop to button
	- expected result: rendered component is not a div but a button
- apply styling in box component
	- expected result: rendered component have the chosen style
- apply styling based on styled-system
	- expected result: rendered component have the chosen style from styled-system
- accept true and false in styling a component with a color
	- expected result: rendered component have or have not the color red
- compose multiple styles together
	- expected result: rendered component have the composed style elements
- use ref to reference to a defined html button element
	- expected result: ref is the defined button element
- render a button component with primary style from a theme via key
	- expected result: rendered button have primary style from the chosen theme
- render a button component with secondary style from a theme via variant
	- expected result: rendered button have secondary style from the chosen theme
- render a button component with primary style from a theme and change a style element
	- expected result: rendered button have primary style with the changed style
