### ISSUE TITLE
Theme setup

### ISSUE THREAD

**Issue by viktoria-schwarz** [reservix-ui/marigold#44]

**Comment by ti10le** [comment]
How do we create a theme?
Which structure do we use?

**Comment by ti10le** [comment]
https://chakra-ui.com/theme is also a good example. Many parts are similarly.
But I don't like something like this:

```
fontSizes: {
    xs: "12px",
    sm: "14px",
    md: "16px",
    lg: "18px",
    xl: "20px",
    "2xl": "24px",
    "3xl": "28px",
    "4xl": "36px",
    "5xl": "48px",
    "6xl": "64px",
  },
```

**Comment by ti10le** [comment]
theme structure like in theme-ui:

- typography
- colors
- styles
- breakpoints
- spacing

**Comment by sebald** [comment]
I would like to (re-)add this to the next iteration. Should we just start out by using `theme-ui` schema for a theme?

**Comment by sebald** [comment]
As a work item, maybe wen can have some typings that reflect existing variants?
E.g. if we have a text component that reads from `theme.text.<variant>` there should be typings for that:

```ts
type BaseTheme = {
	text: {
		body: {},
        headline: {}
        [key: string]: {}
	}
}
```
