### ISSUE TITLE
Documentation for <Box> component

### ISSUE THREAD

**Issue by sebald** [reservix-ui/marigold#84]
# What's in the Box!!!

Initial documentation for the `<Box>` component. The following things should be included:

- [x] difference between theme/css prop/style props/base styles
- [x] application order of theme/css prop/style props/base styles
- [x] `as` property

**Comment by ti10le** [comment]
"usage with theme (themeSection + variant)" will be make after we have the first theme (--> #87)

**Comment by sebald** [comment]
@ti10le Open a new issue if you want to tackle this point later!

**Comment by ti10le** [comment]
#117 Examples are following later
